// web/components/quoteCard.tsx
import { FC } from "react"
import { urlFor } from "lib/utils"
import { QuoteProps } from "lib/interfaces"
import u from "styles/utils.module.scss"
import s from "pages/index.module.scss"

const QuoteCard: FC<QuoteProps> = ({ direction, quote, photograph }) => {
  return (
    <div
      className={`${s.quoteContainer} ${u.flex} ${u.border}`}
      style={{ flexDirection: direction }}
    >
      <img
        src={urlFor(photograph.image).url()}
        alt={photograph.title.en}
        className={`${s.img} ${u.cover} ${u.ofHidden}`}
        decoding="async"
        loading="lazy"
        width="716"
        height="454"
      />
      <div
        className={`${s.quoteText} ${u.relative} ${s.cardPadding} ${u.bgLight}`}
      >
        <img
          alt="Quote Left"
          src="data:image/svg+xml,%3Csvg viewBox='0 0 100 73' xmlns='http://www.w3.org/2000/svg' fill-rule='evenodd' clip-rule='evenodd' stroke-linejoin='round' stroke-miterlimit='2' class='quoteLeft'%3E%3Cpath d='M56.291 47.899c0-11.552 2.962-21.135 8.886-28.751C71.1 11.533 78.219 5.629 86.534 1.435 87.417.92 88.319.552 89.238.331 90.158.11 90.986 0 91.722 0c2.355 0 4.323.773 5.905 2.318C99.209 3.863 100 5.592 100 7.505c0 .956-.276 1.95-.828 2.98-.552 1.03-1.416 1.95-2.594 2.759-4.194 2.796-8.517 6.18-12.969 10.154-4.452 3.973-6.677 9.086-6.677 15.34 5.96 0 10.908 1.362 14.845 4.084 3.937 2.722 5.905 6.879 5.905 12.471 0 5.666-1.913 9.933-5.739 12.803-3.827 2.869-8.168 4.304-13.025 4.304-6.034 0-11.313-2.06-15.839-6.18-4.525-4.121-6.788-10.228-6.788-18.321zM22.627 72.4c-6.034 0-11.314-2.06-15.839-6.18C2.263 62.099 0 55.992 0 47.899c0-11.552 2.962-21.135 8.885-28.751 5.924-7.615 13.043-13.519 21.358-17.713.883-.515 1.784-.883 2.704-1.104C33.867.11 34.695 0 35.43 0c2.355 0 4.323.773 5.906 2.318 1.582 1.545 2.373 3.274 2.373 5.187 0 .956-.276 1.95-.828 2.98-.552 1.03-1.417 1.95-2.594 2.759-4.194 2.796-8.517 6.18-12.969 10.154-4.452 3.973-6.678 9.086-6.678 15.34 5.96 0 10.909 1.362 14.846 4.084 3.936 2.722 5.905 6.879 5.905 12.471 0 5.666-1.913 9.933-5.74 12.803-3.826 2.869-8.168 4.304-13.024 4.304z' fill-rule='nonzero' fill='%23FFF'/%3E%3C/svg%3E"
          className={`${s.quoteLeft} ${u.absolute}`}
          width="81"
          height="59"
        />
        <img
          alt="Quote Right"
          src="data:image/svg+xml,%3Csvg viewBox='0 0 95 73' xmlns='http://www.w3.org/2000/svg' fill-rule='evenodd' clip-rule='evenodd' stroke-linejoin='round' stroke-miterlimit='2' class='quoteRight'%3E%3Cpath d='M94.7 24.501c0 11.552-2.962 21.135-8.885 28.751-5.923 7.615-13.042 13.519-21.357 17.713-.883.515-1.785.883-2.704 1.104-.92.221-1.748.331-2.484.331-2.354 0-4.323-.773-5.905-2.318-1.582-1.545-2.373-3.274-2.373-5.187 0-.956.276-1.95.828-2.98.552-1.03 1.417-1.95 2.594-2.759 4.194-2.796 8.517-6.18 12.969-10.154 4.451-3.973 6.677-9.086 6.677-15.34-5.96 0-10.908-1.362-14.845-4.084-3.937-2.722-5.905-6.879-5.905-12.471 0-5.666 1.913-9.933 5.74-12.803C62.876 1.435 67.217 0 72.074 0c6.033 0 11.313 2.06 15.838 6.18 4.525 4.121 6.788 10.228 6.788 18.321zM21.081 0c6.034 0 11.313 2.06 15.839 6.18 4.525 4.121 6.788 10.228 6.788 18.321 0 11.552-2.962 21.135-8.885 28.751-5.924 7.615-13.043 13.519-21.357 17.713-.883.515-1.785.883-2.705 1.104-.919.221-1.747.331-2.483.331-2.355 0-4.323-.773-5.905-2.318C.791 68.537 0 66.808 0 64.895c0-.956.276-1.95.828-2.98.552-1.03 1.416-1.95 2.594-2.759 4.194-2.796 8.517-6.18 12.968-10.154 4.452-3.973 6.678-9.086 6.678-15.34-5.96 0-10.909-1.362-14.845-4.084-3.937-2.722-5.905-6.879-5.905-12.471 0-5.666 1.913-9.933 5.739-12.803C11.883 1.435 16.225 0 21.081 0z' fill-rule='nonzero' fill='%23FFF'/%3E%3C/svg%3E"
          className={`${s.quoteRight} ${u.absolute}`}
          width="81"
          height="59"
        />
        <blockquote>
          {quote.quote.en}
          <div className={u.lineSpacer}></div>
          <cite className={u.uppercase}>({quote.cite}{", "}{quote.organisation.en})</cite>
        </blockquote>
      </div>
    </div>
  )
}
export default QuoteCard

// svelte/src/lib/QuoteCard.svelte
<script lang="ts">
  // import { t } from "$lib/translations/index.js"
  // import Image from "$lib/Image.svelte"
  import Icon from "$lib/Icon.svelte"
  // import Tredegar from "$img/aen_tredegar.jpg"
  // import quoteLeft from "../icons/quote-left.svg"
  // import quoteRight from "../icons/quote-right.svg"
  export let image: string
  export let width: string
  export let height: string
  export let quote: string
  export let cite: string
</script>

<section class="mb-large">
  <div class="quote__container flex border shadow">
    <img
      src={image}
      width={width}
      height={height}
      alt="Spoken Word at Tredegar House"
      class="img cover of-hidden"
      decoding="async"
      loading="lazy"
    />
    <div class="quote__text relative card-padding bg-light">
      <!-- <img
        alt="Quote Left"
        src={quoteLeft}
        class="quote-left absolute"
      /> -->
      <!-- <img
        alt="Quote Right"
        src={quoteRight}
        class="quote-right absolute"
      /> -->
      <Icon name="quoteLeft" width="100" height="73" class="quote-left absolute fg-white" />
      <Icon name="quoteRight" width="100" height="73" class="quote-right absolute fg-white" />
      <blockquote>
        {quote}
        <div class="line-spacer"></div>
        <cite>{cite}</cite>
      </blockquote>
    </div>
  </div>
</section>

<style lang="scss">
  @use '../styles/foundation/breakpoints' as b;

  .quote__text {
    width: var(--textWidth);
    @include b.mq(md) {
      width: 100%;
    }
  }

  .img {
    object-position: var(--xPosition) 50%;
  }
</style>
