// alpha/components/quoteCard.tsx
import u from "styles/utils.module.scss"
import s from "components/quoteCard.module.scss"

const QuoteCard = () => {
  return (
    <section className={`${s.quote} ${u.mbLarge}`}>
      <div
        className={`${s.quoteContainer} ${u.flex} ${u.border} ${u.shadow}`}
      >
        <img
          src={image}
          width={width}
          height={height}
          alt="Spoken Word at Tredegar House"
          className={`${s.img} ${u.cover} ${u.ofHidden}`}
          decoding="async"
          loading="lazy"
        />
        <div
          className={`${s.quoteText} ${u.relative} ${u.cardPadding} ${u.bgLight}`}
        >
          <img
            alt="Quote Left"
            src={quoteLeft}
            className={`${s.quoteLeft} ${u.absolute}`}
          />
          <img
            alt="Quote Right"
            src={quoteRight}
            className={`${s.quoteRight} ${u.absolute}`}
          />
{/*           <Icon
            name="quoteLeft"
            width="100"
            height="73"
            className="quoteLeft absolute fgWhite"
          />
          <Icon
           name="quoteRight"
           width="100"
           height="73"
           className="quoteRight absolute fgWhite"
          /> */}
          <blockquote>
            {quote}
            <div className={u.lineSpacer}></div>
            <cite>{cite}</cite>
          </blockquote>
        </div>
      </div>
    </section>
  )
}
export default QuoteCard

// svelte/src/lib/QuoteCard.svelte
<script lang="ts">
  // import Image from "$lib/Image.svelte"
  import Icon from "$lib/Icon.svelte"
  // import quoteLeft from "../icons/quote-left.svg"
  // import quoteRight from "../icons/quote-right.svg"
  export let image: string
  export let width: string
  export let height: string
  export let quote: string
  export let cite: string
</script>

<section class="mb-large">
  <div class="quote__container flex border shadow">
    <img
      src={image}
      width={width}
      height={height}
      alt="Spoken Word at Tredegar House"
      class="img cover of-hidden"
      decoding="async"
      loading="lazy"
    />
    <div class="quote__text relative card-padding bg-light">
      <!-- <img
        alt="Quote Left"
        src={quoteLeft}
        class="quote-left absolute"
      /> -->
      <!-- <img
        alt="Quote Right"
        src={quoteRight}
        class="quote-right absolute"
      /> -->
      <Icon name="quoteLeft" width="100" height="73" class="quote-left absolute fg-white" />
      <Icon name="quoteRight" width="100" height="73" class="quote-right absolute fg-white" />
      <blockquote>
        {quote}
        <div class="line-spacer"></div>
        <cite>{cite}</cite>
      </blockquote>
    </div>
  </div>
</section>

<style lang="scss">
  @use '../styles/foundation/breakpoints' as b;

  .quote__text {
    width: var(--textWidth);
    @include b.mq(md) {
      width: 100%;
    }
  }

  .img {
    object-position: var(--xPosition) 50%;
  }
</style>
