// src/components/signUp.tsx
import React from "react"

import IllustrationI from "./illustrations/illustrationI"

const SignUp = ({ signup1, signup2, signup3 }) => (
  <section className="signupSection">
    <IllustrationI />
    <h2 className="signupHeading">{signup1}</h2>
    <div>
      <form>
      <label>
        <input
          type="text"
          name={signup2}
          placeholder={signup2}
          className="signupInput"
        />
      </label>
      <input 
        type="image"
        src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 320 512'%3E%3Cpath d='M285 273L91 467c-9 10-24 10-34 0l-22-22c-10-10-10-25-1-34l155-155L34 101c-9-9-9-24 1-34l22-22c10-10 25-10 34 0l194 194c10 9 10 25 0 34z' fill='%23fff'/%3E%3C/svg%3E"
        alt=""
        style={{
          cursor: `pointer`,
          background: `rgba(77, 73, 73)`,
          border: 0,
          height: `4rem`,
          width: `4rem`,
          padding: `1.2rem`,
          transform: `translateY(1.4rem)`
        }}
      />
    </form>
    </div>
    <div className="signupText">
      <p>{signup3}</p>
    </div>
  </section>
)

export default SignUp

// svelte/src/lib/SignUp.svelte
<script lang="ts">
  import { t } from "$lib/translations/index.js"
  import chevron from "../icons/chevron-right-solid.svg"
</script>

<section class="mb-large text-center">
  <h2>{$t('content.signup-1')}</h2>
  <div>
    <form>
      <label>
        <input
          type="text"
          name={$t('content.signup-2')}
          placeholder={$t('content.signup-2')}
          class="signup__input sans bg-white"
        />
      </label>
      <input
        type="image"
        src={chevron}
        alt=""
        class="signup__send"
      />
    </form>
  </div>
  <div class="signup__text center text-left">
    <p>{$t('content.signup-3')}</p>
  </div>
</section>

<style lang="scss">
  .signup__input {
    border: 0;
    width: 57%;
    padding: 1.5rem 2.7rem;
    font-size: 2.8rem;
    // @include b.mq(md) {
    //   border: 0;
    //   width: calc(88% - 7.2rem);
    // }
    // @include b.mq(sm) {
    //   border: 0;
    //   width: calc(100% - 7.2rem);
    //   padding: 1.5rem 2.7rem;
    //   font-size: 2.7rem;
    // }
  }

  .signup__text {
    width: 50%;
    // @include b.mq(md) {
    //   width: 65%;
    // }
    // @include b.mq(sm) {
    //   text-align: left;
    //   width: 88%;
    //   padding-top: 0.4rem;
    //   margin: auto;
    // }
  }

  .signup__send {
    cursor: pointer;
    background-color: rgba(77, 73, 73);
    border: 0;
    height: 7rem;
    width: 7rem;
    padding: 2.1rem;
    transform: translate(-0.4rem, 2.4rem);
  }
</style>
